library(dplyr)
path<-getwd()
path_file<-"course/project5/"
my_data<-read.table(paste(path,paste(path_file,"household_power_consumption.txt",sep = ""),sep="/"),header = TRUE,sep = ";")
my_data$Date<-as.Date(my_data$Date,"%d/%m/%Y")
my_data$Time<-strptime(paste(my_data$Date,my_data$Time),format ="%Y-%d-%d %H:%M:%S")
my_data<-subset(my_data,Date>='2007-02-01'&Date<='2007-02-02')
par("mfrow"=c(1,1))
png("plot3.png", width=480, height=480)
plot(my_data$Time,as.numeric(levels(my_data$Sub_metering_1))[my_data$Sub_metering_1],type="l",ylab="Energy sub metering",xlab="")
lines(my_data$Time,as.numeric(levels(my_data$Sub_metering_2))[my_data$Sub_metering_2],type="l",col="red")
lines(my_data$Time,my_data$Sub_metering_3,type="l",col="blue")
legend("topright",col = c("black","blue","red"),lty = 1,lwd=2,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()